version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORIES_FRONTEND=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_FRONTEND
      - REPOSITORIES_BACKEND=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_BACKEND
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building Frontend Docker image...
      - docker build -t $REPOSITORIES_FRONTEND:latest -f client/Dockerfile client/
      - docker build -t $REPOSITORIES_FRONTEND:$IMAGE_TAG -f client/Dockerfile client/
      - echo Building Backend Docker image...
      - docker build -t $REPOSITORIES_BACKEND:latest -f server/Dockerfile server/
      - docker build -t $REPOSITORIES_BACKEND:$IMAGE_TAG -f server/Dockerfile server/
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker images...
      - docker push $REPOSITORIES_FRONTEND:latest
      - docker push $REPOSITORIES_FRONTEND:$IMAGE_TAG
      - docker push $REPOSITORIES_BACKEND:latest
      - docker push $REPOSITORIES_BACKEND:$IMAGE_TAG
      - echo Writing image definitions file for ECS...
      - printf '[{"name":"container1","imageUri":"%s"},{"name":"backend-container","imageUri":"%s"}]' $REPOSITORIES_FRONTEND:$IMAGE_TAG $REPOSITORIES_BACKEND:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
